MM&&MMWWw%*%%ww***%%******+===+++*+*++==============-::::;;;;;;;;;;;;;:::::---====++==----::::---==+*%%%wwwwwwmmmmmmmmmmmmmww%ww%%
MMMMMMWmww**%w%+++*******%*===++***+====-----:::::---::;;;;;;;;;;;;;;;;;;;;:--=----::::::::::----=++****%%%wwwwwmmmmmmmmmmmwwwwww%
&&MMMMWmww%%%*+++++**+*%****+++++*+++==----::::::;;;::;;;,,,,,,;;;;;;,,,,,;;::::;;;;;;;:::::--===+****%%%%%wwwwwwwwwwmmmmmmwwmwmmw
&&&MMMMWmmw%%++++++%%**%%********+++==--::::::::::;;;;;;;,,,,,...,,,,,,;,,,,,,,,;;;;;;:::-===+****%***%%%%%wwwmwwwwwmwwwwwwwmmwmmW
&MMM&&&MWWmw%*+=+*******%***%*+++====--:::::::::;;;;;,,,,,,,.,;--:;..,,,,,,,,,,,;;;;;::---===+**%**%www%%wwmmmWmmmwwmm%%%%wwmwwwmm
8&&8888&&MWmw%***********%%%%+======--::::::::;;;;,,,,,,,,.,:*m%%wW%:.,,,,,,,,,;;;;;:::---===+++++*%%wwwwmWWWWWWWmmmWmww%%%wwmmmmm
88&&8888&MMMWmmww%+*******%%%**++====-::::::::;;;;;,,,,,,.,-**,,:=wm&=.,,,,,,,,,;;;;;::-----=++=++*%%%%wwmWWMMWWmmwwmmmmmwwmWWWWWM
8&&&&&MM&MMMWWmw%%************+==---::::::;;::;;;,,,,,,,,.+%w=*+-wWmM&-.,,,,,,,;;;;;;::::--====++++**%wmWWWWWWWmmmwwwmmmmmWWMMWWWW
8&&&MMWMM&&MWWw%%%%***++++++==----:::;;:::;;;;;;,,,,,,,..-wm*:*:*MwwM&w.,,,,,,,,,;;;;;;::---====++++*%%wmWWWmmmww%%%wmmmmWWWWmmmmW
&&MWWmmmWWWWmmwwmw%*++======-----:::;;;;;;;;;;;,,,,,,,,.=ww&+,,=mW**M&&%,,,,,,,,,,,,;;;:::---===++++***%wwmwww%%%****%mWWMMmwwwwww
&MMMWWmmmWWmmmmmmw%*++====-=-:::::;;;;;;;;;;,,,,,,,,,,..mmm8w+%*wWMW8&M&+,,,,,,,,,,;;;:::----=====+++*+*%%%%%%%*****%wmmmmw%w%w%ww
&&&&MWWWWWWWMMWmmww%*****+==--::::;;;;;;;;;,,,,,,,,,,,.;wmM8MW%*wm&8@8WWW,.,,,,,,,,,;;;;;;::::::::-------==++++*%%%%%ww***+*%%%%ww
88&&MMMMMMMMMMWWmwwmmmww%*+==--::::::;;;;,,,,,,,....,,.-wM&MMmM&&8#8@@#MW;....,,,,,,,,,,,,,,;;;;:::::::---===++++++++*%%%%%%%%wwww
888&&MMMMMMMMWWWWmmmWmmw%*+==--:::;;;;;,,,,,,,,.,,.....-mWMMW=+mWMWM###8M+........,,,,,,,,,,,;;;:::-----===+++***+++**%%wwwwwww%ww
&M&MMMMMMMMMMMMWWWWmww%%%**+=-::;;;;;;;;;,,,,,,,...,:*+%WmM8W+:=%wwW888&&+  ......,,,,,,,,,;;;;;:::::---=++******%*%%%%%%%%wwwwwww
MWMMWWWWMMMMMMMmwww%%%%%%*+=-::::;;:::;;;;,,,,,.,;-+mWWWmW%**=-w%%WmM&&&&WW+,......,,,,,,,,,;;;:::::::-=+++++***%%%ww%%%wwwwwwwwmm
WWWWmmWWWWWWmww%**%%**++==---:::::::::;;;;,,,,,;-=++wMm*w=;..;;+--==-%WmMWM8m+-;..,,,,,,,,,;;;:::::------==++****%wmmmWWmmWWWWWWWM
WWWWmWWWWWmmmww%*++========---::::::;;;;;;;,,;-===+%&m*w*,-,,::;;:;:;:%%*mWmMMWW*,.,,,,,,;;;::::--=====---==+*%%%wmWMMMMMMMMM&MMMM
WWWWWWWWmmmmw%*++====--======---:::::::;;;;;-+++===WWm*w:.:;,;-,:;;-;;+w%%MmwWWwW%;..,;;;;;:::--===========+++*wmmmmWMMMMMM&&&&MMM
MMWWWmmmwwww%+++++++========------::::::;:+*%w%+==%WWmw+;,;;;,-;;,-;;;-wmwmMw%mWwWW%:.,;;;::--=========+*%+=++++%wwwwmM&&&&&8&&&&M
MMWmmw%***%*+++++++++==+++===------:::;:=%+::;+++=WmMwW::,:;:;;-,;:;;;-%mmWMMwwWWWWWW=.,;;;::------====+*ww+++++=+wwwmWM&&&&8888&&
MWmw%%%%**+======++++****+++++=---::;:=+=:::;=+++%m&Wmm;:,:;;-;-;;--;:=*mwMM&Wwm&MMMWW-.,;;;;;::::---==+*%%%+****++wmmmWMMMM&&&&88
Wmmww%%**++=====+*%%%*******+==--:--=*=;,;:;:=+**mWMmW%;=;:-;::-:,--;;+%wwm&M&mmWMMM&Wm+;,;;;:::::::---==*%%**%%%%**mWWWWWWWM&&&&8
WWmmw%%**++++++*wmww%%**%%**+===+%%w%;,;;;;;-***mWWm&w%;=-:-:;::;,;=::+%%W%&&&WWmWMMMMWMm=;;::::::--===++*%w%*%%%%ww%WMMMWMMMMM&MM
WWmw%%*****%%%wwwmmwwwwww%**+%mWm*+=;,::-:;;=*%mMwm8&*w--+;::;;::;;===+*%WwW&8&WmW&&MMMMMMw-;:::---=++**%%%%w%%wwwwmw%WWWWMMmmmWMM
mw%%**%%%%%wwmmmmmWWWmw%%%*%%w%*:;;;;;;;=++=*%wWMwM#M+w+:+:::;;:-:;-+==+%WWw&&8MWWMMWWmw%*%w%===+++++***%%*%wwwwwwmmw%wWWWWmwmwwMM
mw%*%%%%wwmmmmmmmwmw%wmWww*+;,;;-=+---:;-+*%*mW&WW&#M%%w=+=;::;:=-;:=+++%MMwM888MWWWw%%*+::%w%+*%w%%%%%w%**wmwmmmmwww%%mmmw%%%%%wm
mmmwwwwwwwmmmmmwmww%%mmmmmww%::=--=-=*%+=+%%mMm8M8&@W%%w%++=+-+%*+-***+++WM%m888&MWWm%***;=*==-::-+**%%+*wmmwwmmwwmww%*%w%%%%%%www
MMWWmmmwwwwmmmwmmmww%*%%mmmmmw===++--+*%mWWwMWW8&8&#M%%%w**%w%WmmmmWm%%%%W&%%&&&8MMmWm***=-+=:;:-::;-*=*mWmwwwwmmmw%********%wwwww
&MMMMWWWmmmmmmWMM&MWM&MM&&&&8Mw*=+*****%%WmwMW88&&&##&MWmmmmmWWWMMM&&&&&&8#m%W&&WWWmwww%+--=++:;=m**mwww*%wwwwmm%**%******%%%%%
&&&MMMMWWmmmWMMMMMM&&&&8888###M%+=+++++%m&WW&M88888#@8&MmmmmmmWWMMMMMMMMMM8&%m&&8#&WWMWwwwwww%*+::*mww%***++%**%wmmww%**++++******
&MMMMMMMWWMM&&&MM&&&&&&&8888&8#Ww*+*%%W8##WMM&8&&88##&MMWwwwmmmmwmmWMMMMMM&&mmM&&88WmWWm%*+**+=:=WWwwwwww%ww%%wmmWmmmw%*++++***%%*
&&&&&M&&&888&&M&&&&&&&&&888&&8##&m*wM&&&8&W&&8#&8&8##mww*-::==:-;=++*WM&8888MWM&&&8MmWW&8Mm*-:=%MMWWmmwww%wwwwwwmmWmwwww%***%wwww%
8&&MM&&&&&&&&&&&&&&&&&&&8888888&&MMMMM&&8WM&&8#&@8%%%==;-=:--:++*;+%*wM&#MM&&&M&&mWMW&m%m&MmWWWWWmwwwww%%%%wwwwwwwww%%%%%%%%
MMMM&&&&&&&MM&M&&&&M&&M&8888&&MmmWMM&&&&&WM&&8#88#8@W%m*-=;-=;===*++-:*+*%w88M&8&&M8MWWWM&8&8&&MWmmWWWWWmmww%%%%%%%wwwwwmw%%%%%%%w
MMM&&&&&&&&MMWMMMWWWWM&&&&MWMMWWMMM&&&&&MWM&&8888#8#w%m+=-;-+;-++++=-;+*%%%W#&&&&&MMM&&8&&&&MMWWWMWwwmmmmmww%%%%wwwmwwwww%%%www
MMMMM&M&&MMMMMMMWWWWWMM&&MMMMMMMMMMM&&&MWWWM8888&8#&%ww==::=*-==+=+=::+*%%%w#8&&&8&&8#8&&&&88&&MMMWM&MWmwmmmmmmwwwwwwmmmmmwwww%%ww
&MM&MMMMMM&&&&MMWWMMMMMM&&&MWWWWWWMMMMWWWMMM888&&&#&*m*=:::-*+=-====--+****%𕬸&8##8&&MM88&MM&&&&MMMWWmmmmwwmmmmmWWmwwww%%%%ww
&&&&MMMMM&&&&&MMMMMMMMMM&MWWmwwmmWWWWmmWWWM&8&&MM88M%w+-::;-%*+:-+==:==***%*W@#88888&8#8&&&&&88&MM88&&MMMMMMMWmmmmWWWWWmww%ww%%%wm
8&&&&MM&&&&&&&MMM&&&&MMMmwwmmmwmmmWWWWWMWWMM&&&MM&#Mww--:::-%*+:=+==--=*%*%%w8#88888&8##8&&&8&&&&MM&8&&&&MMM&&MMMWWMWWmmWWmmmmwwmm
&&&&&&&&&&&&&&MMM&&&&MMWmmmmmmmmmmWWWWWMMWMM&&&MM&8&m%---::=**+-++++--=+%%%ww�#88&888&&&&&&&88&&&&&&&&&MMMMMWWWWWWmmwwwmW
&&&&&&&&&&&&&&&&&&&&&MWWWWWWmWWWWWWWWWWMMM&M&&MWMM88m%:----=++++++++-:=*%w%wwM#8888888&88&M&&&&8&&&&&&&8888888&&&&MMWWWWWWmmwmmWMM
8&88&&&&&M&&&&&&&&&&MMMWWWWWWmmmmWWMMWWMMM&M&&MWWWM8M%-=--:=+++++=*+---*%%%%%W#8&M&888&&8&MMM&&&88&&&&&888888&&&MMMWWWmWmmmWWWWMM&
&&&&MMMMMMM&&&888&&MMMMWWWWWWWmmmWWWWWMM&&&MM&MWmMM&&%*+---++++++++-=--+%%%%wm8&&&&&&&&&&&MMWWM&888&&&&&&&88&&&&&MWMWWWmWWWWMMMM&8
8&&&&MMMMM&&&8888&&MMMMWWmWWWWWWWMMMWMMM&&MMWMWWWM&&&ww%++++++***+-====*w%%%%%MMWMMM&&MMMMMMWmmWM&&&888&&&&&&&&&MMMMMMWWWMM&&&&&&8
88&&&&MMMMM&&&&88&&&MMWWWWWWWWWMMM&&MM&&&&MMMMWWMM&&&mmm%%****%%*+=+++++ww%*%%MMWMWMMMWWWMWWWmmmWWM&&&&&&&&&&&MMMMMMMMMWMM&&&&&888
&&&&&&MMMMM&&&&&&&&&MMMWMWMMWWWWWM&&M&&&&&&&MMMMM&&88WWW%%***%***+++++**www%%%M&MMMWWWWWWWWWmmmmmWWWM&M&&MM&MMMWMMWMMMMWWWM&MM&&&&